title: Prashant Shah
logo: /assets/img/myLogo.jpg
description:
Software Engineer at Yupiteru,
Shizuoka, Japan
Industrial experienced IoT developer
(Two years) through COE with coding
skills and public speaking including
leadership skills.

PHONE:
+977 984-439-1989
+91 903-527-0794 (WhatsApp)

EMAIL:
shahprashant030@gmail.com

SOCIAL MEDIA:
LinkedIn: linkedin.com/in/shahprashant030
Github: github.com/shahprashant030
Instagram: instagram.com/i.prashantshah
Twitter: twitter.com/shahprashant030

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
