title: Prashant Shah
logo: /assets/img/myLogo.jpg
description:
Software Engineer at Yupiteru,<br>
Shizuoka, Japan<br>
Industrial experienced IoT developer
(Two years) through COE with coding
skills and public speaking including
leadership skills.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
